baseURL = 'http://aromatica.github.io/'
languageCode = 'en-us'
title = 'aromatica'

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]